services:
  product:
    build: ./product
    image: k8s-poc_product
    ports:
      - "8080:8080"

  cart:
    build: ./cart
    image: k8s-poc_cart
    ports:
      - "1323:1323"
    environment:
      - REDIS_URL=redis:6379
      - PRODUCT_SERVICE_URL=http://product:8080
      - NATS_URL=nats://nats:4222

  redis:
    image: redis
    ports:
      - "6379:6379"

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  frontend:
    build: ./frontend
    image: k8s-poc_frontend
    ports:
      - "4200:4200"
